# -*- coding: utf-8 -*-
"""k3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NzNVd53km-Wnu6fMNZd3X0ta-Z-ORcWa
"""

import streamlit as st
import pickle
import pandas as pd
model=pickle.load(open('tips_model.pkl','rb'))
st.title("Tip Prediction App")
total_bill=st.number_input("Total Bill")
size=st.number_input("Size")
sex=st.selectbox("Sex",['Male','Female'])
smoker=st.selectbox("smoker",['Yes','No'])
day=st.selectbox("Day",['Thur','Friday','Saturday','Sunday'])
time=st.selectbox("Time",['Lunch','Dinner'])
input_data=pd.DataFrame({
    'total_bill':[total_bill],
    'size':[size],
    'sex':[sex],
    'smoker':[smoker],
    'day':[day],
    'time':[time]
})
if st.button("Predict Tip"):
    prediction=model.predict(input_data)
    st.success(f"Predicted Tip:{prediction[0]:2f}")